mod_name = "Dusks Screenshots"
mod_id = "dusks_screenshots"
mod_group = "com.theendercore"
mod_version = "1.0.0"
mod_description = ""
github_repo = "Teamvoided/DusksScreenshots"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = "*"
